#!/bin/bash

CMD="pull"
if [[ $# > 0 ]]
then
    CMD=$1
fi

for DIR in `ls`
do
    if [[ ! -d ${DIR} ]]
    then
        continue
    fi

    (
        cd ${DIR}
        if [[ -d ".git" ]]
        then
            echo -e "\n\n==========$DIR==========" && git ${CMD}
        else
            (
                for FILE in `ls`
                do
                    ([[ -d ${FILE} ]] && cd ${FILE} && [[ -d ".git" ]] && echo -e "\n\n----------${DIR}/${FILE}----------" && git ${CMD})
                done
            )
        fi
    )
done
